@BASE_URL = http://localhost:3000

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTIyZGJkYjE1MTdjMzE5YTljOWQ3YzEiLCJpYXQiOjE3NjY1NzM0MzgsImV4cCI6MTc5ODEwOTQzOH0.Y8_4GSesB101igo1v8eRy6PK0d8W0lSjGI2_iaN_PB0
### Create a new user
POST {{BASE_URL}}/users
Content-Type: application/json

{
    "name": "Muskan Doe",
    "email": "muskan.doe@example.com",
    "password": "password"
}

### Get all users
GET {{BASE_URL}}/users?limit=1&page=2
Authorization: Bearer {{token}}

### Get user by id
GET {{BASE_URL}}/users/6922dbdb1517c319a9c9d7c1

### Update user by id
PATCH {{BASE_URL}}/users/6922dbdb1517c319a9c9d7c1
Content-Type: application/json

{
    "email": "jack.doe@example.com"
}

### Delete user by id
DELETE {{BASE_URL}}/users/6922dbdb1517c319a9c9d7c1

### Create a new baggage
POST {{BASE_URL}}/693e9c0b9f21f09230294cff/baggages
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Red Suitcase"
}

### Get all baggage
GET {{BASE_URL}}/baggages
Authorization: Bearer {{token}}

### Get baggage by id
GET {{BASE_URL}}/693e9c0b9f21f09230294cff/baggages
Authorization: Bearer {{token}}

### Update baggage
PATCH {{BASE_URL}}/6947d47655b7b448ddd190b5
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Blue Suitcase",
    "completed": true
}

### Delete baggage
DELETE {{BASE_URL}}/693e9c0b9f21f09230294cff/baggages/6945308e860c5fd018a21e4f
Authorization: Bearer {{token}}

### Login user
POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
    "email": "jack.doe@example.com",
    "password": "password"
}

### create a new trip
POST {{BASE_URL}}/trips
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title":"Trip to the moon",
    "startDate" :"2025-12-15",
    "endDate":"2025-12-16",
    "budget":{
        "total":1000
    },
    "destinations":["Moon","Mars","Jupiter"]

}

### Get all trips
GET {{BASE_URL}}/trips
Authorization: Bearer {{token}}

### Get trip by id
GET {{BASE_URL}}/trips/693e9c0b9f21f09230294cff
Authorization: Bearer {{token}}

### Update trip
PATCH {{BASE_URL}}/trips/693e9c0b9f21f09230294cff
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title":"Trip to the Saturn"
}

### Delete trip
DELETE {{BASE_URL}}/trips/693e9c0b9f21f09230294cff
Authorization: Bearer {{token}}

### Create a new itinerary
POST {{BASE_URL}}/693e9c0b9f21f09230294cff/itineraries
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title":"Visit the lunar base",
    "description":"Tour of the moon base",
    "date":"2025-12-15",
    "activities":[
        {
            "name":"Lunar rover ride",
            "time":"10:00 AM",
            "description":"Ride the lunar rover around the moon base",
            "notes":[
                "Wear comfortable clothes",
                "Bring sunscreen"
            ]

        },
        {
            "name":"Moonwalk",
            "time":"2:00 PM"
            "description":"Walk on the surface of the moon",
            "notes":[
                "Stay close to the base",
                "Follow safety protocols"
            ]
        }
    ]
}

### Get all itineraries
GET {{BASE_URL}}/693e9c0b9f21f09230294cff/itineraries
Authorization: Bearer {{token}}

### Get itinerary by id
GET {{BASE_URL}}/itineraries/6950f4e2d3f4c8b1e4a7c9d2
Authorization: Bearer {{token}}

### Update itinerary
PATCH {{BASE_URL}}/itineraries/6950f4e2d3f4c8b1e4a7c9d2
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title":"Visit the Mars base"
}

### Delete itinerary
DELETE {{BASE_URL}}/itineraries/6950f4e2d3f4c8b1e4a7c9d2
Authorization: Bearer {{token}}

### Invite collaborator to trip
POST {{BASE_URL}}/trips/693e9c0b9f21f09230294cff/invite
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "collaboratorEmails": [
        "dbhattarai387@gmail.com",
        "niteshkdk619@gmail.com",
        "pranish.dahal980@gmail.com"
    ]
}

